### ISSUE TITLE
codes for CPGM-AAE

### ISSUE THREAD

**Issue by feiyangsb** [BraveGump/CGDL-for-Open-Set-Recognition#5]
Hello,

I am very interested in CPGM-AAE, but I  am confused about the center-learning phase. 

Are you planning to publish your codes for training CPGM-AAE, or could you please explain it more detailly about this part?

Thanks

**Comment by BraveGump** [comment]
> Hello,
> 
> I am very interested in CPGM-AAE, but I am confused about the center-learning phase.
> 
> Are you planning to publish your codes for training CPGM-AAE, or could you please explain it more detailly about this part?
> 
> Thanks

Certainly, we will publish codes.  For your question, the certer-learning phase is exactly the same as CPGM-VAE.

**Comment by feiyangsb** [comment]
> > Hello,
> > I am very interested in CPGM-AAE, but I am confused about the center-learning phase.
> > Are you planning to publish your codes for training CPGM-AAE, or could you please explain it more detailly about this part?
> > Thanks
> 
> Certainly, we will publish codes. For your question, the certer-learning phase is exactly the same as CPGM-VAE.


Thanks!
